publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }

    repositories {
        // Expandium Maven Repository
        maven {
            url = version.toString().endsWith("-SNAPSHOT") ? "https://repo.expandium.net/snapshots" : "https://repo.expandium.net/releases"
            allowInsecureProtocol = true
            credentials {
                username = System.getenv("MAVEN_USER") ?: ""
                password = System.getenv("MAVEN_TOKEN") ?: ""
            }
        }

        // GitHub Packages Maven Repository
        if (System.getenv("GITHUB_REPOSITORY") != null) {
            maven {
                name = "GitHubPackages"
                url = "https://maven.pkg.github.com/${System.getenv("GITHUB_REPOSITORY")}"
                credentials {
                    username = System.getenv("GITHUB_ACTOR") ?: "x-access-token"
                    password = System.getenv("GITHUB_TOKEN") ?: ""
                }
            }
        }
    }
}
